branches:
  - name: master
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: eslint
      releaseRules:
        - tag: Fix
          release: patch
        - tag: Build
          release: patch
        - tag: Upgrade
          release: patch
        - tag: Chore
          release: patch
        - tag: Update
          release: minor
        - tag: New
          release: minor
        - tag: Breaking
          release: major
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: breaking
            section: Breaking Changes
          - type: new
            section: New
          - type: update
            section: Updates
          - type: fix
            section: Bug Fixes
          - type: chore
            section: Refactorings
          - type: upgrade
            section: Dependency Updates
          - type: build
            section: Build System Improvements
  - - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: |-
        sed -i "s/^Latest Version: .*/Latest Version: ${nextRelease.version}/" Readme.MD
        sed -i "s/^version=.*/version=${nextRelease.version}/" gradle.properties
        sed -i "s/^version=.*/version=${nextRelease.version}/" antlr-kotlin-examples-mpp/gradle.properties
        sed -i "s/^\\([[:space:]]*\\)\\(ext.projectVersion[[:space:]]*=[[:space:]]*\\)'.*'/\\1\\2'${nextRelease.version}'/" antlr-kotlin-examples-js/build.gradle
  - - "@semantic-release/git"
    - assets:
        - Readme.md
        - CHANGELOG.md
        - gradle.properties
        - antlr-kotlin-examples-mpp/gradle.properties
        - antlr-kotlin-examples-js/build.gradle
      message: "Release: ${nextRelease.version}\n\n${nextRelease.notes}"
