name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    if: github.event.commits[0].author.name != 'semantic-release-bot'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java:
          - '8'
          - '11'
          - '17'

    name: Build with Java ${{ matrix.Java }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: ci.sh
        run: ./ci.sh
        env:
          MAVEN_GROUP_ID: ${{ vars.MAVEN_GROUP_ID }}

  release:
    runs-on: ubuntu-latest
    needs: build

    if: github.ref == 'refs/heads/master'

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        with:
          additional_packages: |
            ['@semantic-release/commit-analyzer','@semantic-release/release-notes-generator','@semantic-release/changelog','@semantic-release/exec','@semantic-release/git','conventional-changelog-eslint','conventional-changelog-conventionalcommits']
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
